# Generated by Django 5.0.2 on 2024-03-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='username',
        ),
    ]
