# Generated by Django 5.0.2 on 2024-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0002_rename_student_name_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
            ],
        ),
    ]
