# Generated by Django 5.0.2 on 2024-03-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0005_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
