# Generated by Django 5.0.2 on 2024-03-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0009_alter_event_options_event_organizers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.AddField(
            model_name='organizer',
            name='organized_events',
            field=models.ManyToManyField(related_name='event_organizers', related_query_name='event_organizer', to='festapp.event'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizers',
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, null=True, related_name='organizer_events', related_query_name='organizer_event', to='festapp.organizer'),
        ),
    ]
