# Generated by Django 5.0.2 on 2024-03-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0010_alter_event_options_organizer_organized_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='festapp.organizer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organizer_events', related_query_name='organizer_event', to='festapp.organizer'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organized_events',
            field=models.ManyToManyField(related_name='organizer_events', related_query_name='organizer_event', to='festapp.event'),
        ),
    ]
