# Generated by Django 5.0.2 on 2024-03-04 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0011_event_event_organizer_alter_event_organizers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='event_type',
        ),
    ]
