# Generated by Django 5.0.2 on 2024-03-03 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0011_remove_event_organizers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='winning_user',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, null=True, related_name='organizer_events', related_query_name='organizer_event', to='festapp.organizer'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='organized_events',
            field=models.ManyToManyField(related_name='event_organizers', related_query_name='event_organizer', to='festapp.event'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festapp.event'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
