# Generated by Django 5.0.2 on 2024-03-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0013_remove_event_organizers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', related_query_name='organizer', to='festapp.event'),
        ),
    ]
