# Generated by Django 5.0.2 on 2024-03-04 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0014_alter_customuser_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='thumbnail',
        ),
    ]
