# Generated by Django 5.0.2 on 2024-03-04 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festapp', '0015_remove_event_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_organizer',
        ),
    ]
